### ISSUE TITLE
Public Google Calendar

### ISSUE THREAD

**Issue by wannadrunk** [creatorsgarten/techcal.dev#111]
ไม่แน่ใจว่า calendar engine เป็นอะไร ปกติใน Google Calendar สามารถที่จะทำ shared calendar ได้ ตัวอย่างเช่น ปฏิทินวันหยุดประจำปี 

techcal สามารถทำได้หรือไม่ แทนที่จะ export iCal แล้วไป import

**Comment by dtinth** [comment]
@wannadrunk เหมือนตอนนี้ขั้นตอนรายละเอียนบนหน้าเว็บยังเขียนไว้ไม่ถูกต้อง

วิธี Subscribe คือ ไม่ต้องโหลดไฟล์ iCal ครับ คลิกขวาแล้วกด Copy Link Address แล้วเอา URL ไปใช้ Subscribe ได้เลย

ส่วนอันนี้คือ Public calendar link ครับ น่าจะสามารถกดแอดได้ https://calendar.google.com/calendar/embed?src=tech.cal.th%40gmail.com&ctz=Asia%2FBangkok

ถ้าสะดวกส่ง PR มาอัพเดตข้อความบนเว็บได้นะครับ 🙏

**Comment by wannadrunk** [comment]
ขอบคุณมากครับ

ทำ PR ไม่เป็นครับ
