### ISSUE TITLE
Add an English version?

### ISSUE THREAD

**Issue by elektronik2k5** [creatorsgarten/techcal.dev#7]
Hi and thanks for creating this calendar! :bowing_man: 

I found it hard to subscribe to the calendar without knowing Thai. Please consider adding English.
If that's outside the scope of the project, feel free to close this issue :).

**Comment by saiqulhaq** [comment]
Hi @rayriffy 
Is there a good localization library for the Svelte app?
It looks the app is based on the Svelte framework now
